on: [push]

jobs:
  git:
    runs-on: ubuntu-latest
    name: Build git for debian.
    steps:
    - name: Make a build shell
      run: |
        echo 'echo "deb-src http://deb.debian.org/debian/ buster main" >> /etc/apt/sources.list' > run.sh
        echo 'echo "deb-src http://security.debian.org/debian-security buster/updates main" >> /etc/apt/sources.list' >> run.sh
        echo 'echo "deb-src http://deb.debian.org/debian/ buster-updates main" >> /etc/apt/sources.list' >> run.sh
        echo 'apt-get update' >> run.sh
        echo 'apt-get upgrade' >> run.sh
        echo 'apt-get build-dep git -y' >> run.sh
        echo 'apt-get install --no-install-recommends wget -y' >> run.sh
        echo 'apt-get install --no-install-recommends ca-certificates make libssl-dev libghc-zlib-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip -y' >> run.sh
        echo 'wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.29.2.tar.gz' >> run.sh
        echo 'tar -xzvf git-2.29.2.tar.gz' >> run.sh
        echo 'cd git-2.29.2' >> run.sh
        echo './configure --prefix=/tmp/BUILD' >> run.sh
        echo 'make && make install' >> run.sh
        echo 'tar -czvf /github/workspace/git.tgz /tmp/BUILD' >> run.sh
        cat run.sh
    - name: Build git
      id: build
      uses: zhuduiyou/BUILDTGZ@v0.1
    - name: Upload git
      id: upload
      uses: actions/upload-artifact@v2
      with:
        name: git
        path: /home/runner/work/BUILDTGZ/BUILDTGZ/git.tgz
